# Generated by Django 4.2.1 on 2023-05-24 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_website_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dns_server',
        ),
        migrations.AlterField(
            model_name='website',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 9, 31, 12, 414213, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='website',
            name='owner',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='client',
            name='dns_server',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
